name: Messenger Bot CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Generate dynamic .env
        run: |
          echo "BOT_NAME=${{ github.event.repository.name }}" >> .env
          echo "OWNER=${{ github.event.head_commit.author.name }}" >> .env
          echo "EMAIL=${{ github.event.head_commit.author.email }}" >> .env
          echo "USERNAME=${{ github.repository_owner }}" >> .env
          echo "BRANCH=${{ github.ref_name }}" >> .env
          echo "FB_APPSTATE=${{ secrets.FB_APPSTATE }}" >> .env

      - name: Start the bot
        env:
          PORT: 8080
        run: npm start
